j_queryj_query:
    resource: "@jQueryjQueryBundle/Controller/"
    type:     annotation
    prefix:   /

_home:
    pattern:  /
    defaults: { _controller: casamunozempresaBundle:Default:index }

casamunozempresa:
    resource: "@casamunozempresaBundle/Controller/"
    type:     annotation
    prefix:   /
    
    
some_identifier: 
    resource: "@casamunozempresaBundle/Controller/NaturalController.php" 
    type: annotation  
    
    

 
