_home:
    pattern:  /
    defaults: { _controller: casamunozempresaBundle:Default:index }
    
casamunozempresa:
    resource: "@casamunozempresaBundle/Controller/"
    type:     annotation
    prefix:   /
    
login:
    pattern: /login
    defaults: { _controller: casamunozempresaBundle:Security:login }
 
login_check:
    pattern: /login_check
 
logout:
    pattern: /logout

